export const CHARACTER_TYPES = {
  1: {
    type: "warrior",
    name: "melvis",
    color: "#00aaff",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 96,
      spriteHeight: 96,
      basePath: "assets/melvis/",
      animations: {
        idle: { src: "IDLE.png", frames: 2, frameDuration: 0.1 },
        running: { src: "IDLE.png", frames: 2, frameDuration: 0.05 },
        attacking: { src: "ATTACK1.png", frames: 1, frameDuration: 0.06 },
        attacking2: { src: "ATTACK2.png", frames: 1, frameDuration: 0.06 },
        hurt: { src: "IDLE.png", frames: 2, frameDuration: 0.1 },
        blocking: { src: "IDLE.png", frames: 1, frameDuration: 0.1 },
      },
    },
  },
  2: {
    type: "ninja",
    name: "Shadow Ninja",
    color: "#9900ff",
    useSprite: false,
  },
  3: {
    type: "samurai",
    name: "Pixel Samurai",
    color: "#ff6600",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 96,
      spriteHeight: 96,
      basePath: "assets/Sprites/",
      animations: {
        idle: { src: "IDLE.png", frames: 10, frameDuration: 0.1 },
        running: { src: "RUN.png", frames: 16, frameDuration: 0.05 },
        attacking: { src: "ATTACK 1.png", frames: 7, frameDuration: 0.06 },
        hurt: { src: "HURT.png", frames: 4, frameDuration: 0.1 },
        blocking: { src: "IDLE.png", frames: 1, frameDuration: 0.1 },
      },
    },
  },
  4: {
    type: "dark-samurai",
    name: "Dark Samurai",
    color: "#6600aa",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites2/Samurai/",
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 8, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 6, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 3, frameDuration: 0.1 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 2, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 2, frameDuration: 0.1 },
        dead: { src: "Dead.png", frames: 3, frameDuration: 0.15 },
      },
    },
  },
  5: {
    type: "shinobi",
    name: "Shinobi",
    color: "#0066aa",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites2/Shinobi/",
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 8, frameDuration: 0.05 },
        attacking: { src: "Attack_1.png", frames: 5, frameDuration: 0.06 },
        attacking2: { src: "Attack_2.png", frames: 3, frameDuration: 0.1 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.07 },
        hurt: { src: "Hurt.png", frames: 2, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 4, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 3, frameDuration: 0.15 },
      },
    },
  },
  6: {
    type: "street-fighter",
    name: "Street Fighter",
    color: "#aa6600",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites2/Fighter/",
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 8, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 4, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 3, frameDuration: 0.1 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.12 },
        blocking: { src: "Shield.png", frames: 2, frameDuration: 0.1 },
        dead: { src: "Dead.png", frames: 3, frameDuration: 0.15 },
      },
    },
  },
  7: {
    type: "gotoku",
    name: "Gotoku",
    color: "#ff3300",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites3/Gotoku/",
      animations: {
        idle: { src: "Idle.png", frames: 5, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 7, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 4, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 4, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 4, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 5, frameDuration: 0.15 },
        scream: { src: "Scream.png", frames: 4, frameDuration: 0.1 },
        jump: { src: "Jump.png", frames: 8, frameDuration: 0.08 },
      },
    },
  },
  8: {
    type: "onre",
    name: "Onre",
    color: "#00ff66",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites3/Onre/",
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 7, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 5, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 4, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 7, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 6, frameDuration: 0.15 },
        flight: { src: "Flight.png", frames: 6, frameDuration: 0.08 },
        scream: { src: "Scream.png", frames: 7, frameDuration: 0.1 },
      },
    },
  },
  9: {
    type: "yurei",
    name: "Yurei",
    color: "#9933ff",
    useSprite: true,
    spriteConfig: {
      spriteWidth: 128,
      spriteHeight: 128,
      basePath: "assets/sprites3/Yurei/",
      animations: {
        idle: { src: "Idle.png", frames: 5, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 5, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 4, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 4, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 7, frameDuration: 0.08 },
        attacking4: { src: "Attack_4.png", frames: 7, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 4, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 4, frameDuration: 0.15 },
        charge1: { src: "Charge_1.png", frames: 4, frameDuration: 0.1 },
        charge2: { src: "Charge_2.png", frames: 4, frameDuration: 0.1 },
        scream: { src: "Scream.png", frames: 4, frameDuration: 0.1 },
      },
    },
  },
  10: {
    type: "graffiti-artist",
    name: "Graffiti Artist",
    color: "#ff00aa",
    useSprite: true,
    customScale: 1.25, // Half of normal 2.5 scale because sprites are 256x256 instead of 128x128
    spriteConfig: {
      spriteWidth: 256,
      spriteHeight: 256,
      basePath: "assets/Graffiti_Artist_3/",
      animations: {
        idle: { src: "Idle.png", frames: 7, frameDuration: 0.1 },
        running: { src: "Walk.png", frames: 10, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 6, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 4, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 10, frameDuration: 0.07 },
        hurt: { src: "Hurt_1.png", frames: 5, frameDuration: 0.12 },
        hurt2: { src: "Hurt_2.png", frames: 4, frameDuration: 0.15 },
        blocking: { src: "Idle.png", frames: 1, frameDuration: 1 },
        dead: { src: "K.O..png", frames: 9, frameDuration: 0.15 },
        jump: { src: "Jump.png", frames: 9, frameDuration: 0.08 },
        jumpShot: { src: "Jump_shot.png", frames: 18, frameDuration: 0.05 },
      },
    },
  },
  11: {
    type: "gorgon",
    name: "Gorgon",
    color: "#05840e",
    useSprite: true,
    spriteConfig: {
      basePath: "assets/Gorgon_1/",
      spriteWidth: 128,
      spriteHeight: 128,
      animations: {
        idle: { src: "Idle.png", frames: 7, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 7, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 16, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 7, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 10, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 5, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 3, frameDuration: 0.15 },
      },
    },
  },
  12: {
    type: "minotaur",
    name: "Minotaur",
    color: "#4f2222",
    useSprite: true,
    spriteConfig: {
      basePath: "assets/Minotaur/",
      spriteWidth: 128,
      spriteHeight: 128,
      animations: {
        idle: { src: "Idle.png", frames: 10, frameDuration: 0.1 },
        attacking: { src: "Attack.png", frames: 5, frameDuration: 0.07 },
        running: { src: "Walk.png", frames: 12, frameDuration: 0.06 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Idle.png", frames: 1, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 5, frameDuration: 0.15 },
      },
    },
  },
  13: {
    type: "zombie",
    name: "Zombie",
    color: "#576d00",
    useSprite: true,
    spriteConfig: {
      basePath: "assets/Zombie/",
      spriteWidth: 128,
      spriteHeight: 128,
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Walk.png", frames: 10, frameDuration: 0.06 },
        attacking: { src: "Attack.png", frames: 5, frameDuration: 0.07 },
        hurt: { src: "Hurt.png", frames: 4, frameDuration: 0.15 },
        blocking: { src: "Idle.png", frames: 1, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 5, frameDuration: 0.15 },
      },
    },
  },
  14: {
    type: "samorai",
    name: "Samorai",
    color: "#7e00b4",
    useSprite: true,
    spriteConfig: {
      basePath: "assets/Samurai/",
      spriteWidth: 128,
      spriteHeight: 128,
      animations: {
        idle: { src: "Idle.png", frames: 6, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 8, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 4, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 5, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 3, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 2, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 4, frameDuration: 0.15 },
      },
    },
  },
  15: {
    type: "samurai_commander",
    name: "Samurai Commander",
    color: "#927200",
    useSprite: true,
    spriteConfig: {
      basePath: "assets/Samurai_Commander/",
      spriteWidth: 128,
      spriteHeight: 128,
      animations: {
        idle: { src: "Idle.png", frames: 5, frameDuration: 0.1 },
        running: { src: "Run.png", frames: 8, frameDuration: 0.06 },
        attacking: { src: "Attack_1.png", frames: 4, frameDuration: 0.07 },
        attacking2: { src: "Attack_2.png", frames: 5, frameDuration: 0.08 },
        attacking3: { src: "Attack_3.png", frames: 4, frameDuration: 0.08 },
        hurt: { src: "Hurt.png", frames: 2, frameDuration: 0.15 },
        blocking: { src: "Shield.png", frames: 2, frameDuration: 0.08 },
        dead: { src: "Dead.png", frames: 6, frameDuration: 0.15 },
      },
    },
  },
};
